### PR TITLE
Revert "Compiles"

### PR DESCRIPTION
**Pull request by barryWarnock**
Reverts barryWarnock/concurrent-asteroids#19 I was foolish and only gave this a quick glance before merging. This will not actually compile, the various empty <>s on list declarations throw errors and there is a ClassNotFoundException in main.Main:

> Exception in thread "main" java.lang.ClassNotFoundException: main.Main
>   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>   at java.lang.Class.forName0(Native Method)
>   at java.lang.Class.forName(Class.java:264)
>   at com.intellij.rt.execution.application.AppMain.main(AppMain.java:122)

### CODE REVIEW

**Comment by JeremyBolster** [comment]
Have you tried updating the location of main since it moved?

**Comment by barryWarnock** [comment]
Wouldn't any move be reflected automatically by git?

**Comment by JeremyBolster** [comment]
The IDE still has to be told where the main method is.

**Comment by barryWarnock** [comment]
weird, IDEA claimed to know where the main method was but deleting it and cloning it again was the only way to make it work.

**Comment by JeremyBolster** [comment]
Also filing in <> on the right side causes a compiler warning and is definitely not required.

**Comment by barryWarnock** [comment]
Yea I'm not sure whats up with that I was getting a compile error from that before I re-cloned everything then it was fine.

**Pull request merged**
